/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-15 11:26:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; chatset=utf-8;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"http://people.iola.dk/olau/flot/jquery.flot.js\"></script>\r\n");
      out.write("<script\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction load() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'controller',\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tsuccess : function(json) {\r\n");
      out.write("\t\t\t\tif (json != null) {\r\n");
      out.write("\t\t\t\t\tvar data = JSON.parse(json);\r\n");
      out.write("\t\t\t\t\tif (data.ramRecords != null) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar d1 = [ null ];\r\n");
      out.write("\t\t\t\t\t\t$.plot($(\"#placeholder1\"), [ d1 ]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tfor (var i = 0; i < data.ramRecords.length; i += 1)\r\n");
      out.write("\t\t\t\t\t\t\td1.push([i,data.ramRecords[i].available/1000000000]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$.plot($(\"#placeholder1\"), [ {\r\n");
      out.write("\t\t\t\t\t\t\tdata : d1,\r\n");
      out.write("\t\t\t\t\t\t\tlines : {\r\n");
      out.write("\t\t\t\t\t\t\t\tsteps : true\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t} ]);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (data.cpuRecords != null) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar d1 = [ null ];\r\n");
      out.write("\t\t\t\t\t\t$.plot($(\"#placeholder2\"), [ d1 ]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tfor (var i = 0; i < data.cpuRecords.length; i += 1)\r\n");
      out.write("\t\t\t\t\t\t\td1.push([i,\tdata.cpuRecords[i].available/10000000000 ]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$.plot($(\"#placeholder2\"), [ {\r\n");
      out.write("\t\t\t\t\t\t\tdata : d1,\r\n");
      out.write("\t\t\t\t\t\t\tlines : {\r\n");
      out.write("\t\t\t\t\t\t\t\tsteps : true\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}]);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(json) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar d1 = [ null ];\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$.plot($(\"#placeholder1\"), [ d1 ]);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$.plot($(\"#placeholder2\"), [ d1 ]);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\tsetInterval(load, 1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"#ram\" data-toggle=\"tab\">RAM</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#cpu\" data-toggle=\"tab\">CPU</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"ram\">\r\n");
      out.write("\t\t\t\t\t<h1>График количества свободной оперативной память:</h1>\r\n");
      out.write("\t\t\t\t\t<div id=\"placeholder1\" style=\"width: 600px; height: 300px;\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"cpu\">\r\n");
      out.write("\t\t\t\t\t<h1>График количества процессорного времени:</h1>\r\n");
      out.write("\t\t\t\t\t<div id=\"placeholder2\" style=\"width: 600px; height: 300px;\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
